"""Generate notebooks/*.ipynb. Notebooks are never edited by hand (CLAUDE.md): edit this file.

    uv run python scripts/make_notebook.py           # (re)write every notebook
    uv run python scripts/make_notebook.py --check   # exit 1 if a committed notebook is stale

Cells are plain Python (no `!` or `%` magics) so tests can compile every one of them.
No --limit: this writes notebooks and processes no rows; the notebook's own settings cell
carries the row limits.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from collections.abc import Callable
from pathlib import Path

import nbformat
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

NOTEBOOK_DIR = Path(__file__).resolve().parents[1] / "notebooks"

Cell = tuple[str, str]  # ("md" | "code", source)


def kaggle_train() -> list[Cell]:
    return [
        (
            "md",
            """\
# Tollgate: fine-tune and calibrate-ready logits on Kaggle (2x T4)

Runs top to bottom on a fresh Kaggle notebook with no local state. Setup (accelerator, Internet,
secrets) is in `notebooks/README.md`.

1. Check the GPU.
2. Install `tollgate[gpu]` from your git repo.
3. Read `HF_TOKEN` from Kaggle secrets, pull the labelled dataset from the Hub, and rebuild the
   query text its license kept out of the Hub copy.
4. Fine-tune Laya: fp16, sdpa attention, a resumable checkpoint every `SAVE_EVERY` steps in
   `/kaggle/working/`, a progress bar, and a clean stop after `BUDGET_HOURS`.
5. Score the calibration and test splits once and save **raw logits** to
   `logits_calibration.npz` and `logits_test.npz`. Calibration and every metric are then fitted
   on a CPU from these files.
6. Push the checkpoint, the logits and `run_metadata.json` to the Hub model repo, under
   `runs/<RUN_NAME>/`.
7. Print exactly what was uploaded and where.

Generated by `scripts/make_notebook.py`. Edit that, not this notebook.""",
        ),
        (
            "code",
            """\
# --- settings: edit these, then Run All -------------------------------------------------------
from datetime import UTC, datetime

NOTEBOOK_STARTED = datetime.now(UTC)

REPO_URL = "https://github.com/ihemanthc/tollgate.git"  # public, so no GITHUB_TOKEN needed
REPO_REF = "main"  # branch, tag or commit sha to install
HF_REPO_DATA = "tollgate-routing-data"  # dataset repo `tollgate push-dataset` wrote
HF_REPO_MODEL = "tollgate-router"  # model repo this run is pushed to (created private)
RUN_NAME = "laya"
RESUME = False  # True: continue runs/<RUN_NAME>/last from the Hub after a session ran out

# Training: TrainConfig's defaults (tollgate/train/train.py), i.e. the real run.
EPOCHS = 3
BATCH_SIZE = 8  # queries per micro-batch; each query is 3 sequences (tier, tools, rag)
GRAD_ACCUM = 2
LR = 2e-5
PATIENCE = 2  # holdout evals without improvement before early stopping
EVAL_EVERY = 500  # optimizer steps between holdout evals (0 = once per epoch)
SAVE_EVERY = 500  # optimizer steps between resumable checkpoints in /kaggle/working
SEED = 0
BUDGET_HOURS = 10.0  # training stops cleanly after this; Kaggle ends sessions at 12 h
EXPORT_BATCH = 64
ALL_ROWS = 10**9  # "every row" for --limit""",
        ),
        ("md", "## 1. GPU"),
        (
            "code",
            """\
import warnings

import torch

assert torch.cuda.is_available(), (
    "No GPU in this session: Settings > Accelerator > GPU T4 x2, then restart the session."
)
GPU_NAME = torch.cuda.get_device_name(0)
print(f"GPU: {GPU_NAME} x{torch.cuda.device_count()}, compute capability "
      f"{'.'.join(map(str, torch.cuda.get_device_capability(0)))}")
if not any(tag in GPU_NAME for tag in ("T4", "P100")):
    warnings.warn(
        f"{GPU_NAME} is not a T4/P100: batch size and the time budget were sized for those.",
        stacklevel=1,
    )
print("Training uses the first GPU; the second T4 stays idle.")""",
        ),
        (
            "md",
            """\
## 2. Install `tollgate[gpu]`

The same as `pip install git+<repo>#egg=tollgate[gpu]`, written in the PEP 508 form current pip
expects. For a private repo, add a `GITHUB_TOKEN` secret (read-only). It reaches git through
environment variables, never the command line, so it cannot appear in pip's output.""",
        ),
        (
            "code",
            """\
import importlib.metadata
import os
import subprocess
import sys

assert "YOUR-USER" not in REPO_URL, "set REPO_URL in the settings cell to your tollgate repo"
pip_env = dict(os.environ)
try:
    from kaggle_secrets import UserSecretsClient

    github_token = UserSecretsClient().get_secret("GITHUB_TOKEN")
except Exception:
    github_token = None  # public repo: no token needed
if github_token:
    pip_env.update(
        GIT_CONFIG_COUNT="1",
        GIT_CONFIG_KEY_0=f"url.https://x-access-token:{github_token}@github.com/.insteadOf",
        GIT_CONFIG_VALUE_0="https://github.com/",
    )
spec = f"tollgate[gpu] @ git+{REPO_URL}@{REPO_REF}"
subprocess.run([sys.executable, "-m", "pip", "install", "--quiet", spec], check=True, env=pip_env)
del github_token, pip_env

from tollgate.train import kaggle as tk  # noqa: E402 -- importable only after the install

print("tollgate", importlib.metadata.version("tollgate"), "commit", tk.installed_commit())""",
        ),
        (
            "md",
            """\
## 3. Hugging Face token and dataset

The Hub copy of the dataset omits LMSYS-Chat-1M query text, because its license forbids
redistribution. It is rebuilt here from the official source, using **your** Hugging Face access
(the account behind `HF_TOKEN` must have accepted the LMSYS-Chat-1M terms), so the text never
passes through a Tollgate repo. Rows that cannot be rebuilt are dropped and counted.""",
        ),
        (
            "code",
            """\
from tollgate import hub, paths
from tollgate.collect.publish import restore_dataset

os.environ["HF_TOKEN"] = tk.kaggle_secret("HF_TOKEN")  # raises with setup steps if missing
os.environ.update(
    TOLLGATE_DATA_DIR="/kaggle/working/data",
    TOLLGATE_OUT_DIR="/kaggle/working",
    HF_REPO_DATA=HF_REPO_DATA,
    HF_REPO_MODEL=HF_REPO_MODEL,
)
DATA_REPO = hub.resolve_repo_id(HF_REPO_DATA)
DATASET_REVISION = hub.dataset_revision()
public_copy = hub.pull_dataset(dest_dir=paths.data_dir() / "hub", revision=DATASET_REVISION)
RESTORE = restore_dataset(public_copy, paths.dataset_path())
print(f"dataset {DATA_REPO}@{DATASET_REVISION[:12]}: {RESTORE.rows} rows")
print(f"withheld rebuilt: {RESTORE.recovered} of {RESTORE.withheld}; dropped {RESTORE.dropped}")""",
        ),
        (
            "md",
            """\
## 4. Train

fp16 autocast with a GradScaler (Turing has no bf16) and sdpa attention are applied by
`tollgate train` on CUDA. A resumable `last/` is written every `SAVE_EVERY` steps. After
`BUDGET_HOURS` the run writes `last/` and stops cleanly; set `RESUME = True` and run the
notebook again to continue.""",
        ),
        (
            "code",
            """\
import time

from tollgate.train.train import BEST_DIR, LAST_DIR, train_laya

RUN_DIR = paths.checkpoints_dir() / RUN_NAME
resume_from = None
if RESUME:
    resume_from = hub.pull_checkpoint(f"runs/{RUN_NAME}/{LAST_DIR}")
    try:
        hub.pull_checkpoint(f"runs/{RUN_NAME}/{BEST_DIR}")
    except hub.HubError:
        print("no best/ on the Hub yet; it will be written at the next holdout eval")

train_started = time.perf_counter()
RESULT = train_laya(
    limit=ALL_ROWS, epochs=EPOCHS, batch_size=BATCH_SIZE, grad_accum=GRAD_ACCUM, lr=LR,
    patience=PATIENCE, eval_every=EVAL_EVERY, save_every=SAVE_EVERY, seed=SEED,
    device="cuda", amp=True, resume_from=resume_from, run_name=RUN_NAME,
    max_hours=BUDGET_HOURS, progress=True,
)
TRAIN_SECONDS = time.perf_counter() - train_started
print(f"best step {RESULT.best_step}, holdout loss {RESULT.best_val_loss}, "
      f"budget exhausted: {RESULT.budget_exhausted}")""",
        ),
        (
            "md",
            """\
## 5. Raw logits for the calibration and test splits

One fp32 pass with the `best/` checkpoint, options in canonical order. These are the numbers
CPU serving computes and `tollgate calibrate --logits` fits temperatures on.""",
        ),
        (
            "code",
            """\
from tollgate.schema import Split
from tollgate.train.infer import export_logits, load_logits

LOGITS = [
    export_logits(RUN_DIR / BEST_DIR, split, limit=ALL_ROWS, batch_size=EXPORT_BATCH,
                  device="cuda", progress=True)
    for split in (Split.CALIBRATION, Split.TEST)
]
for path in LOGITS:
    data = load_logits(path)
    print(path.name, len(data["query_id"]), "rows,",
          {k: v.shape for k, v in data.items() if k.startswith("logits_")})""",
        ),
        ("md", "## 6. Push to the Hub"),
        (
            "code",
            """\
META = tk.write_metadata(
    tk.run_metadata(
        RUN_DIR, RESULT, gpu=tk.gpu_info(), dataset_repo=DATA_REPO,
        dataset_revision=DATASET_REVISION, restore=RESTORE, logits=LOGITS,
        started_at=NOTEBOOK_STARTED, finished_at=datetime.now(UTC),
        session_train_s=TRAIN_SECONDS,
    ),
    RUN_DIR,
)
# last/ (weights + optimizer state) only goes up when the run must be resumed.
UPLOADS = tk.push_run(
    RUN_DIR, [*LOGITS, META, RUN_DIR / "history.json"], include_last=RESULT.budget_exhausted
)""",
        ),
        ("md", "## 7. What was uploaded, and where"),
        (
            "code",
            """\
print(tk.format_manifest(UPLOADS, {"dataset": f"{DATA_REPO}@{DATASET_REVISION}"}))
print()
if RESULT.budget_exhausted:
    print("Training ran out of budget: set RESUME = True and run this notebook again.")
print("On your machine:")
print(f"  uv run tollgate pull-run --run {RUN_NAME}")
print(f"  uv run tollgate calibrate --checkpoint checkpoints/{RUN_NAME}/best "
      f"--logits checkpoints/{RUN_NAME}/logits_calibration.npz")""",
        ),
    ]


def kaggle_collect() -> list[Cell]:
    return [
        (
            "md",
            """\
# Tollgate: build the labelled dataset on Kaggle (2x T4), open models only

Runs top to bottom on a fresh Kaggle notebook with no local state and no LLM API key. Every
role is an open model served by Ollama on the GPUs. Setup (accelerator, Internet, secrets) is
in `notebooks/README.md`.

1. Check the GPUs.
2. Install `tollgate[collect]` from your git repo, and Ollama.
3. Read `HF_TOKEN`, point every role at its Ollama model, and optionally restore a previous
   session's cache.
4. Draw the seed prompts.
5. Answer every prompt at each tier, one model at a time: two T4s cannot hold them all.
6. Judge every cheaper answer against the frontier answer and assemble the dataset.
7. Publish it to the Hub dataset repo, with restricted text removed.
8. Print what was built. `kaggle_train.ipynb` trains on it next.

Every model call is cached, so re-running a cell or the whole notebook never calls a model twice
for the same prompt.

Generated by `scripts/make_notebook.py`. Edit that, not this notebook.""",
        ),
        (
            "code",
            """\
# --- settings: edit these, then Run All -------------------------------------------------------
REPO_URL = "https://github.com/ihemanthc/tollgate.git"  # public, so no GITHUB_TOKEN needed
REPO_REF = "main"  # branch, tag or commit sha to install
HF_REPO_DATA = "tollgate-routing-data"  # dataset repo to publish to (created private)
PUBLISH = True  # False: build and stage the dataset, upload nothing

LIMIT = 300  # seed prompts; every one is answered at all three tiers
SOURCES = "lmsys-chat-1m,gsm8k,mmlu"  # lmsys-chat-1m needs its license accepted on HF_TOKEN

# local_small is fixed to ollama/qwen2.5:7b (tollgate.config.LOCAL_SMALL_MODEL): the model the
# router serves locally, so its labels must come from the same one. The judge must not be the
# frontier model, and is best from another family than the candidates.
MODELS = {
    "mid_tier": "ollama/qwen2.5:14b",
    "frontier": "ollama/qwen2.5:32b",
    "judge": "ollama/mistral-small:24b",
}
# (USD per million input tokens, per million output tokens) that a hosted provider charges for
# the same model. None records $0, and every cost in the dataset is fixed when the call is made.
PRICES: dict[str, tuple[float, float] | None] = {"mid_tier": None, "frontier": None}

PARALLEL = 4  # requests one model serves at once
CONTEXT_LENGTH = 8192  # tokens per request: query, answers and judge prompt must fit
RESUME_FROM = ""  # a previous version's data dir, e.g. "/kaggle/input/<this-notebook>/data\"""",
        ),
        ("md", "## 1. GPUs"),
        (
            "code",
            """\
import torch

assert torch.cuda.is_available(), (
    "No GPU in this session: Settings > Accelerator > GPU T4 x2, then restart the session."
)
for i in range(torch.cuda.device_count()):
    props = torch.cuda.get_device_properties(i)
    print(f"GPU {i}: {props.name}, {props.total_memory / 2**30:.0f} GiB")
if torch.cuda.device_count() < 2:
    print("One GPU: the 32B frontier model will not fit; choose smaller MODELS.")""",
        ),
        (
            "md",
            """\
## 2. Install `tollgate[collect]` and Ollama

The repo is cloned, not only pip-installed, because publishing renders the dataset card from
`docs/DATASET_CARD.md`. For a private repo, add a `GITHUB_TOKEN` secret (read-only). It reaches
git through environment variables, never the command line.""",
        ),
        (
            "code",
            """\
import os
import shutil
import subprocess
import sys
from pathlib import Path

assert "YOUR-USER" not in REPO_URL, "set REPO_URL in the settings cell to your tollgate repo"
SRC = Path("/tmp/tollgate")
git_env = dict(os.environ)
try:
    from kaggle_secrets import UserSecretsClient

    github_token = UserSecretsClient().get_secret("GITHUB_TOKEN")
except Exception:
    github_token = None  # public repo: no token needed
if github_token:
    git_env.update(
        GIT_CONFIG_COUNT="1",
        GIT_CONFIG_KEY_0=f"url.https://x-access-token:{github_token}@github.com/.insteadOf",
        GIT_CONFIG_VALUE_0="https://github.com/",
    )
shutil.rmtree(SRC, ignore_errors=True)
subprocess.run(["git", "clone", "--quiet", REPO_URL, str(SRC)], check=True, env=git_env)
subprocess.run(["git", "-C", str(SRC), "checkout", "--quiet", REPO_REF], check=True)
subprocess.run(
    [sys.executable, "-m", "pip", "install", "--quiet", f"{SRC}[collect]"], check=True
)
del github_token, git_env

from tollgate.collect import kaggle as ck  # noqa: E402 -- importable only after the install

COMMIT = subprocess.run(
    ["git", "-C", str(SRC), "rev-parse", "HEAD"], capture_output=True, text=True, check=True
).stdout.strip()
print("tollgate commit", COMMIT)
print(ck.install_ollama())""",
        ),
        (
            "md",
            """\
## 3. Token, models and previous state

`HF_TOKEN` streams the seed sources (LMSYS-Chat-1M is gated) and publishes the dataset.
Collection state lives in `/kaggle/working/data`, so a saved version keeps it. To continue
from one, add its output as input and set `RESUME_FROM`.""",
        ),
        (
            "code",
            """\
from tollgate import paths
from tollgate.config import check_judge_independent, judge_config, tier_config
from tollgate.schema import TIER_ORDER, Tier

os.environ["HF_TOKEN"] = ck.kaggle_secret("HF_TOKEN")  # raises with setup steps if missing
os.environ["TOLLGATE_DATA_DIR"] = "/kaggle/working/data"  # kept by Save Version
OLLAMA = ck.OllamaSettings(parallel=PARALLEL, context_length=CONTEXT_LENGTH)  # logs to data dir
os.environ.update(
    TOLLGATE_OUT_DIR=str(SRC),  # docs/DATASET_CARD.md, and staging under reports/
    HF_REPO_DATA=HF_REPO_DATA,
    **ck.ollama_env(OLLAMA),
    **ck.role_env(MODELS, PRICES),
)
TIERS = [tier_config(t) for t in TIER_ORDER]
JUDGE = judge_config()
check_judge_independent(JUDGE.model, [t.model for t in TIERS if t.tier is Tier.FRONTIER])
for role, cfg in [*((t.tier.value, t) for t in TIERS), ("judge", JUDGE)]:
    ck.ollama_tag(cfg.model)  # every role must be served by Ollama here
    price = PRICES.get(role)
    cost = "$0" if price is None else f"${price[0]} in / ${price[1]} out per M tokens"
    print(f"{role:<12} {cfg.model:<28} {cost}")
if RESUME_FROM:
    print("restored:", ck.restore_state(Path(RESUME_FROM)))""",
        ),
        (
            "md",
            """\
## 4. Seed prompts

The first `LIMIT` prompts, interleaved across `SOURCES`, long and duplicate prompts dropped.
Deterministic, so a resumed session draws the same prompts.""",
        ),
        (
            "code",
            """\
from collections import Counter

from tollgate.collect.pipeline import ensure_seed
from tollgate.collect.runner import load_records

SOURCE_LIST = [s.strip() for s in SOURCES.split(",") if s.strip()]
RECORDS = load_records(ensure_seed(LIMIT, SOURCE_LIST), LIMIT)
print(f"{len(RECORDS)} prompts:", dict(sorted(Counter(r.source for r in RECORDS).items())))""",
        ),
        (
            "md",
            """\
## 5. Answer every prompt at each tier

One model at a time: pull it, answer all prompts, remove it. A tier whose calls all succeeded is
deleted from disk; one with failures keeps its weights, and the next step retries only the
failed prompts. Progress is logged about every 5%.""",
        ),
        (
            "code",
            """\
from tollgate.collect.runner import run_tiers

SERVER = ck.start_ollama(OLLAMA)
TIER_EXIT = {}
for cfg in TIERS:
    print(f"== {cfg.tier.value}: {cfg.model}")
    ck.pull(cfg.model, OLLAMA)
    TIER_EXIT[cfg.tier.value] = ck.call(
        run_tiers, limit=LIMIT, tiers=cfg.tier.value, local_concurrency=PARALLEL
    )
    if TIER_EXIT[cfg.tier.value] == 0:
        ck.remove(cfg.model, OLLAMA)
print("exit codes:", TIER_EXIT)""",
        ),
        (
            "md",
            """\
## 6. Judge and assemble the dataset

`tollgate collect-all` replays every tier answer from the cache, retries any that failed, asks
the judge whether each cheaper answer is as good as the frontier one, and labels each query with
the cheapest tier that was. It prints the label distribution and the split sizes.""",
        ),
        (
            "code",
            """\
from tollgate.collect.pipeline import collect_all

ck.pull(JUDGE.model, OLLAMA)
code = ck.call(collect_all, limit=LIMIT, sources=SOURCES, local_concurrency=PARALLEL)
assert code == 0, f"collect-all exited {code}; its error is above. Re-run this cell to retry."
ck.remove(JUDGE.model, OLLAMA)
if SERVER is not None:
    SERVER.terminate()""",
        ),
        (
            "md",
            """\
## 7. Publish to the Hub

Restricted source text (LMSYS-Chat-1M) is replaced by its sha256; `kaggle_train.ipynb` rebuilds
it under your own license acceptance. With `PUBLISH = False` the files are only staged.""",
        ),
        (
            "code",
            """\
from tollgate.collect.publish import push_dataset_cmd

code = ck.call(push_dataset_cmd, yes=PUBLISH)
assert code == 0, f"push-dataset exited {code}; its error is above."
# The seed holds source text whose license forbids redistribution: keep it out of this
# notebook's saved output. A resumed session draws it again.
paths.seed_path().unlink(missing_ok=True)""",
        ),
        ("md", "## 8. What was built"),
        (
            "code",
            """\
import pandas as pd

from tollgate import hub
from tollgate.collect.pipeline import ledger_totals

DATASET = pd.read_parquet(paths.dataset_path(), columns=["tier", "split"])
print(f"{len(DATASET)} labelled queries from {len(RECORDS)} prompts at commit {COMMIT[:12]}")
print(pd.crosstab(DATASET["tier"], DATASET["split"], margins=True))
print("cost ledger (USD by stage):", ledger_totals(paths.ledger_path()))
if PUBLISH:
    print(f"published: https://huggingface.co/datasets/{hub.resolve_repo_id(HF_REPO_DATA)}")
    print("Next: kaggle_train.ipynb with the same HF_REPO_DATA.")""",
        ),
    ]


NOTEBOOKS: dict[str, Callable[[], list[Cell]]] = {
    "kaggle_train.ipynb": kaggle_train,
    "kaggle_collect.ipynb": kaggle_collect,
}


def ruff_format(source: str) -> str:
    """Code cells in ruff's own style, so `ruff format` never rewrites a generated notebook."""
    done = subprocess.run(
        [sys.executable, "-m", "ruff", "format", "--stdin-filename", "notebooks/cell.py", "-"],
        input=source,
        capture_output=True,
        text=True,
        check=True,
        cwd=NOTEBOOK_DIR.parent,
    )
    return done.stdout.rstrip("\n")


def build(cells: list[Cell]) -> nbformat.NotebookNode:
    nb = new_notebook(
        cells=[
            new_markdown_cell(source, id=f"cell-{i:02d}")
            if kind == "md"
            else new_code_cell(ruff_format(source), id=f"cell-{i:02d}")
            for i, (kind, source) in enumerate(cells)
        ],
        metadata={
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"},
            "accelerator": "nvidiaTeslaT4",
        },
    )
    nbformat.validate(nb)
    return nb


def render(name: str) -> str:
    return nbformat.writes(build(NOTEBOOKS[name]())) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="fail if a notebook is stale")
    args = parser.parse_args()
    stale = []
    for name in NOTEBOOKS:
        path = NOTEBOOK_DIR / name
        text = render(name)
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(name)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8", newline="\n")
            print(f"wrote {path}")
    if stale:
        print(f"stale: {stale}; run scripts/make_notebook.py", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
