"""Generate notebooks/*.ipynb. Notebooks are never edited by hand (CLAUDE.md): edit this file.

    uv run python scripts/make_notebook.py           # (re)write every notebook
    uv run python scripts/make_notebook.py --check   # exit 1 if a committed notebook is stale

Cells are plain Python (no `!` or `%` magics) so tests can compile every one of them.
No --limit: this writes notebooks and processes no rows; the notebook's own settings cell
carries the row limits.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from collections.abc import Callable
from pathlib import Path

import nbformat
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

NOTEBOOK_DIR = Path(__file__).resolve().parents[1] / "notebooks"

Cell = tuple[str, str]  # ("md" | "code", source)


def kaggle_train() -> list[Cell]:
    return [
        (
            "md",
            """\
# Tollgate: fine-tune and calibrate-ready logits on Kaggle (2x T4)

Runs top to bottom on a fresh Kaggle notebook with no local state. Setup (accelerator, Internet,
secrets) is in `notebooks/README.md`.

1. Check the GPU.
2. Install `tollgate[gpu]` from your git repo.
3. Read `HF_TOKEN` from Kaggle secrets, pull the labelled dataset from the Hub, and rebuild the
   query text its license kept out of the Hub copy.
4. Fine-tune Laya: fp16, sdpa attention, a resumable checkpoint every `SAVE_EVERY` steps in
   `/kaggle/working/`, a progress bar, and a clean stop after `BUDGET_HOURS`.
5. Score the calibration and test splits once and save **raw logits** to
   `logits_calibration.npz` and `logits_test.npz`. Calibration and every metric are then fitted
   on a CPU from these files.
6. Push the checkpoint, the logits and `run_metadata.json` to the Hub model repo, under
   `runs/<RUN_NAME>/`.
7. Print exactly what was uploaded and where.

Generated by `scripts/make_notebook.py`. Edit that, not this notebook.""",
        ),
        (
            "code",
            """\
# --- settings: edit these, then Run All -------------------------------------------------------
from datetime import UTC, datetime

NOTEBOOK_STARTED = datetime.now(UTC)

REPO_URL = "https://github.com/ihemanthc/tollgate.git"  # public, so no GITHUB_TOKEN needed
REPO_REF = "main"  # branch, tag or commit sha to install
HF_REPO_DATA = "tollgate-routing-data"  # dataset repo `tollgate push-dataset` wrote
HF_REPO_MODEL = "tollgate-router"  # model repo this run is pushed to (created private)
RUN_NAME = "laya"
RESUME = False  # True: continue runs/<RUN_NAME>/last from the Hub after a session ran out

# Training: TrainConfig's defaults (tollgate/train/train.py), i.e. the real run.
EPOCHS = 3
BATCH_SIZE = 8  # queries per micro-batch; each query is 3 sequences (tier, tools, rag)
GRAD_ACCUM = 2
LR = 2e-5
PATIENCE = 2  # holdout evals without improvement before early stopping
EVAL_EVERY = 500  # optimizer steps between holdout evals (0 = once per epoch)
SAVE_EVERY = 500  # optimizer steps between resumable checkpoints in /kaggle/working
SEED = 0
BUDGET_HOURS = 10.0  # training stops cleanly after this; Kaggle ends sessions at 12 h
EXPORT_BATCH = 64
ALL_ROWS = 10**9  # "every row" for --limit""",
        ),
        ("md", "## 1. GPU"),
        (
            "code",
            """\
import warnings

import torch

assert torch.cuda.is_available(), (
    "No GPU in this session: Settings > Accelerator > GPU T4 x2, then restart the session."
)
GPU_NAME = torch.cuda.get_device_name(0)
print(f"GPU: {GPU_NAME} x{torch.cuda.device_count()}, compute capability "
      f"{'.'.join(map(str, torch.cuda.get_device_capability(0)))}")
if not any(tag in GPU_NAME for tag in ("T4", "P100")):
    warnings.warn(
        f"{GPU_NAME} is not a T4/P100: batch size and the time budget were sized for those.",
        stacklevel=1,
    )
print("Training uses the first GPU; the second T4 stays idle.")""",
        ),
        (
            "md",
            """\
## 2. Install `tollgate[gpu]`

The same as `pip install git+<repo>#egg=tollgate[gpu]`, written in the PEP 508 form current pip
expects. For a private repo, add a `GITHUB_TOKEN` secret (read-only). It reaches git through
environment variables, never the command line, so it cannot appear in pip's output.""",
        ),
        (
            "code",
            """\
import importlib.metadata
import os
import subprocess
import sys

assert "YOUR-USER" not in REPO_URL, "set REPO_URL in the settings cell to your tollgate repo"
pip_env = dict(os.environ)
try:
    from kaggle_secrets import UserSecretsClient

    github_token = UserSecretsClient().get_secret("GITHUB_TOKEN")
except Exception:
    github_token = None  # public repo: no token needed
if github_token:
    pip_env.update(
        GIT_CONFIG_COUNT="1",
        GIT_CONFIG_KEY_0=f"url.https://x-access-token:{github_token}@github.com/.insteadOf",
        GIT_CONFIG_VALUE_0="https://github.com/",
    )
spec = f"tollgate[gpu] @ git+{REPO_URL}@{REPO_REF}"
subprocess.run([sys.executable, "-m", "pip", "install", "--quiet", spec], check=True, env=pip_env)
del github_token, pip_env

from tollgate.train import kaggle as tk  # noqa: E402 -- importable only after the install

print("tollgate", importlib.metadata.version("tollgate"), "commit", tk.installed_commit())""",
        ),
        (
            "md",
            """\
## 3. Hugging Face token and dataset

The Hub copy of the dataset omits LMSYS-Chat-1M query text, because its license forbids
redistribution. It is rebuilt here from the official source, using **your** Hugging Face access
(the account behind `HF_TOKEN` must have accepted the LMSYS-Chat-1M terms), so the text never
passes through a Tollgate repo. Rows that cannot be rebuilt are dropped and counted.""",
        ),
        (
            "code",
            """\
from tollgate import hub, paths
from tollgate.collect.publish import restore_dataset

os.environ["HF_TOKEN"] = tk.kaggle_secret("HF_TOKEN")  # raises with setup steps if missing
os.environ.update(
    TOLLGATE_DATA_DIR="/kaggle/working/data",
    TOLLGATE_OUT_DIR="/kaggle/working",
    HF_REPO_DATA=HF_REPO_DATA,
    HF_REPO_MODEL=HF_REPO_MODEL,
)
DATA_REPO = hub.resolve_repo_id(HF_REPO_DATA)
DATASET_REVISION = hub.dataset_revision()
public_copy = hub.pull_dataset(dest_dir=paths.data_dir() / "hub", revision=DATASET_REVISION)
RESTORE = restore_dataset(public_copy, paths.dataset_path())
print(f"dataset {DATA_REPO}@{DATASET_REVISION[:12]}: {RESTORE.rows} rows")
print(f"withheld rebuilt: {RESTORE.recovered} of {RESTORE.withheld}; dropped {RESTORE.dropped}")""",
        ),
        (
            "md",
            """\
## 4. Train

fp16 autocast with a GradScaler (Turing has no bf16) and sdpa attention are applied by
`tollgate train` on CUDA. A resumable `last/` is written every `SAVE_EVERY` steps. After
`BUDGET_HOURS` the run writes `last/` and stops cleanly; set `RESUME = True` and run the
notebook again to continue.""",
        ),
        (
            "code",
            """\
import time

from tollgate.train.train import BEST_DIR, LAST_DIR, train_laya

RUN_DIR = paths.checkpoints_dir() / RUN_NAME
resume_from = None
if RESUME:
    resume_from = hub.pull_checkpoint(f"runs/{RUN_NAME}/{LAST_DIR}")
    try:
        hub.pull_checkpoint(f"runs/{RUN_NAME}/{BEST_DIR}")
    except hub.HubError:
        print("no best/ on the Hub yet; it will be written at the next holdout eval")

train_started = time.perf_counter()
RESULT = train_laya(
    limit=ALL_ROWS, epochs=EPOCHS, batch_size=BATCH_SIZE, grad_accum=GRAD_ACCUM, lr=LR,
    patience=PATIENCE, eval_every=EVAL_EVERY, save_every=SAVE_EVERY, seed=SEED,
    device="cuda", amp=True, resume_from=resume_from, run_name=RUN_NAME,
    max_hours=BUDGET_HOURS, progress=True,
)
TRAIN_SECONDS = time.perf_counter() - train_started
print(f"best step {RESULT.best_step}, holdout loss {RESULT.best_val_loss}, "
      f"budget exhausted: {RESULT.budget_exhausted}")""",
        ),
        (
            "md",
            """\
## 5. Raw logits for the calibration and test splits

One fp32 pass with the `best/` checkpoint, options in canonical order. These are the numbers
CPU serving computes and `tollgate calibrate --logits` fits temperatures on.""",
        ),
        (
            "code",
            """\
from tollgate.schema import Split
from tollgate.train.infer import export_logits, load_logits

LOGITS = [
    export_logits(RUN_DIR / BEST_DIR, split, limit=ALL_ROWS, batch_size=EXPORT_BATCH,
                  device="cuda", progress=True)
    for split in (Split.CALIBRATION, Split.TEST)
]
for path in LOGITS:
    data = load_logits(path)
    print(path.name, len(data["query_id"]), "rows,",
          {k: v.shape for k, v in data.items() if k.startswith("logits_")})""",
        ),
        ("md", "## 6. Push to the Hub"),
        (
            "code",
            """\
META = tk.write_metadata(
    tk.run_metadata(
        RUN_DIR, RESULT, gpu=tk.gpu_info(), dataset_repo=DATA_REPO,
        dataset_revision=DATASET_REVISION, restore=RESTORE, logits=LOGITS,
        started_at=NOTEBOOK_STARTED, finished_at=datetime.now(UTC),
        session_train_s=TRAIN_SECONDS,
    ),
    RUN_DIR,
)
# last/ (weights + optimizer state) only goes up when the run must be resumed.
UPLOADS = tk.push_run(
    RUN_DIR, [*LOGITS, META, RUN_DIR / "history.json"], include_last=RESULT.budget_exhausted
)""",
        ),
        ("md", "## 7. What was uploaded, and where"),
        (
            "code",
            """\
print(tk.format_manifest(UPLOADS, {"dataset": f"{DATA_REPO}@{DATASET_REVISION}"}))
print()
if RESULT.budget_exhausted:
    print("Training ran out of budget: set RESUME = True and run this notebook again.")
print("On your machine:")
print(f"  uv run tollgate pull-run --run {RUN_NAME}")
print(f"  uv run tollgate calibrate --checkpoint checkpoints/{RUN_NAME}/best "
      f"--logits checkpoints/{RUN_NAME}/logits_calibration.npz")""",
        ),
    ]


NOTEBOOKS: dict[str, Callable[[], list[Cell]]] = {"kaggle_train.ipynb": kaggle_train}


def ruff_format(source: str) -> str:
    """Code cells in ruff's own style, so `ruff format` never rewrites a generated notebook."""
    done = subprocess.run(
        [sys.executable, "-m", "ruff", "format", "--stdin-filename", "notebooks/cell.py", "-"],
        input=source,
        capture_output=True,
        text=True,
        check=True,
        cwd=NOTEBOOK_DIR.parent,
    )
    return done.stdout.rstrip("\n")


def build(cells: list[Cell]) -> nbformat.NotebookNode:
    nb = new_notebook(
        cells=[
            new_markdown_cell(source, id=f"cell-{i:02d}")
            if kind == "md"
            else new_code_cell(ruff_format(source), id=f"cell-{i:02d}")
            for i, (kind, source) in enumerate(cells)
        ],
        metadata={
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"},
            "accelerator": "nvidiaTeslaT4",
        },
    )
    nbformat.validate(nb)
    return nb


def render(name: str) -> str:
    return nbformat.writes(build(NOTEBOOKS[name]())) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="fail if a notebook is stale")
    args = parser.parse_args()
    stale = []
    for name in NOTEBOOKS:
        path = NOTEBOOK_DIR / name
        text = render(name)
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(name)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8", newline="\n")
            print(f"wrote {path}")
    if stale:
        print(f"stale: {stale}; run scripts/make_notebook.py", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
